### ISSUE TITLE
Attempt to lookup a bearer unknown to RadioDNS results in an NXDOMAIN exception being raised

### ISSUE THREAD

**Issue by adriancross** [radiodns/pyradiodns#2]
When calling one of the RadioDNS class's lookup_\* methods with values that do not correspond to a RadioDNS fqdn an NXDOMAIN exception is raised.

This is a little unfriendly as the caller has to handle low-level dns resolver issues.

**Comment by nickpiggott** [comment]
I think this is intended functionality, which you can trap outside the function?
