### ISSUE TITLE
ImportError: No module named parse with dnspython-2.0.0 on Debian Jessie

### ISSUE THREAD

**Issue by UlrikBrinck** [radiodns/pyradiodns#4]
Hi Nick, as requested I create an issue here.

When I install pyradiodns using
pip install setuptools
sudo python setup.py install

And then use the odr-radioepg-bridge, I get this error:
File "build/bdist.linux-x86_64/egg/dns/resolver.py", line 19, in <module>
ImportError: No module named parse

This might have something to do with dnspython-2.0.0. It seems I don't have this problem with dnspython-1.16.0.

**Comment by nickpiggott** [comment]
dnspython-2.0.0 will only work on Python >=3.6 (https://www.dnspython.org/news/2.0.0/).

I've adjusted setup.py script to require only version 1.16.0

**Comment by nickpiggott** [comment]
Great, thanks for confirming.
